name: Backend CI
on:
  push:
    branches:
      - main  # Trigger CI on pushes to the main branch
    paths:
      - 'backend/**'  # Only trigger when backend files change
  workflow_dispatch:  # Add this to enable manual triggering
jobs:
  test:
    name: Run Backend Tests
    runs-on: self-hosted
    environment: MONGO_URI  # Environment for secrets
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
        
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm ci  # Clean install using package-lock.json
        
    - name: Run Backend Tests
      working-directory: ./backend
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
      run: npm test
      
    # Optional: Deploy if tests pass
    - name: Deploy Backend Changes
      if: success()
      working-directory: ./backend
      run: |
        # Create .env file securely without printing contents
        echo "${{ secrets.PROD }}" > .env
        
        # Restart only the backend service with zero downtime
        pm2 reload backend || pm2 start backend